version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cyber_db
    restart: always
    environment:
      POSTGRES_USER: cyber_user
      POSTGRES_PASSWORD: cyber_password
      POSTGRES_DB: cyber_mon_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cyber_user -d cyber_mon_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cyber_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://cyber_user:cyber_password@db:5432/cyber_mon_db
    volumes:
      - ./backend:/app
      - file_storage:/storage
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cyber_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - internal_network
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:alpine
    container_name: cyber_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - internal_network
  # === Тунель Ngrok ===
  ngrok:
    image: ngrok/ngrok:latest
    container_name: cyber_ngrok
    restart: always
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=3CyVaxAMF1uM9d0KLl75npk8zga_6c1Txdz3756MAz3WXcRcA
    command: http nginx:80 --log=stdout
    depends_on:
      - nginx
    networks:
      - internal_network
networks:
  internal_network:
    driver: bridge

volumes:
  postgres_data:
  file_storage:
