"""Initial models

Revision ID: adde9bbce2d8
Revises: 
Create Date: 2026-04-26 17:32:14.646223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adde9bbce2d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SELF_ASSESSMENT', 'EXTERNAL_ASSESSMENT', name='reporttype'), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'RETURNED', 'APPROVED', name='reportstatus'), nullable=True),
    sa.Column('total_score_part1', sa.Float(), nullable=True),
    sa.Column('total_score_part2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('is_signed_kep', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['template_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('control_type', sa.Enum('BOOLEAN', 'SELECT', 'TEXT', 'FILE_UPLOAD', name='controltype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['template_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('score_multiplier', sa.Float(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['template_controls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('auditor_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['template_controls.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['control_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_answers')
    op.drop_table('control_options')
    op.drop_table('template_controls')
    op.drop_table('template_categories')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('template_parts')
    op.drop_table('report_templates')
    op.drop_table('organizations')
    # ### end Alembic commands ###
