"""add_evidence_file_path

Revision ID: f90baee4863f
Revises: adde9bbce2d8
Create Date: 2026-04-26 18:39:43.888599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90baee4863f'
down_revision: Union[str, None] = 'adde9bbce2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_answers', sa.Column('evidence_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_answers', 'evidence_file_path')
    # ### end Alembic commands ###
